### ISSUE TITLE
Quiz-App

### ISSUE THREAD

**Issue by friskycodeur** [friskycodeur/curated-project-list#10]
- [x] Add code files for Quiz-App
- [x] Add a readme file for Quiz-App (refer to other projects for format)
- [x] Mention resources used in creating the app.
- [x] (OPTIONAL) Deploy on netlify and share the link in readme.

P.S -> Create a new folder for the project inside the JavaScript Project. If already there then make changes to the existing one.

**Comment by Neeleshp22** [comment]
Can you please assign me this issue.
