### ISSUE TITLE
Grocery List

### ISSUE THREAD

**Issue by friskycodeur** [friskycodeur/curated-project-list#12]
- [ ]  Add code files for Grocery List.
- [ ]  Add a readme file for Grocery List (refer to other projects for format)
- [ ]  Mention resources used in creating the app.
- [ ]  (OPTIONAL) Deploy on netlify and share the link in readme.

P.S -> Create a new folder for the project inside the JavaScript Project. If already there then make changes to the existing one.

**Comment by adhamale2810** [comment]
I would like to work on this project. Please assign the issue.

**Comment by friskycodeur** [comment]
Sure @adhamale2810 , assigning you the Grocery List task.

**Comment by adhamale2810** [comment]
Hi @friskycodeur, I have completed the project using node express js. Can I host it on Heroku?

**Comment by rachit-geek** [comment]
@adhamale2810 Ok deploy it.!

**Comment by adhamale2810** [comment]
Pls review my PR @friskycodeur
