### ISSUE TITLE
TIC-TAC-TOE

### ISSUE THREAD

**Issue by friskycodeur** [friskycodeur/curated-project-list#13]
- [x]  Add code files for TIC-TAC-TOE.
- [x]  Add a readme file for TIC-TAC-TOE (refer to other projects for format)
- [x]  Mention resources used in creating the app.
- [x]  (OPTIONAL) Deploy on netlify and share the link in readme.

P.S -> Create a new folder for the project inside the JavaScript Project. If already there then make changes to the existing one.

**Comment by rudrakshi99** [comment]
@friskycodeur Please assign this issue to me.

**Comment by friskycodeur** [comment]
Assigning this issue to you @rudrakshi99 .
