### ISSUE TITLE
Review Carousel

### ISSUE THREAD

**Issue by friskycodeur** [friskycodeur/curated-project-list#14]
- [x]  Add code files for Review Carousel
- [x]  Add a readme file for Review Carousel (refer to other projects for format)
- [x]  Mention resources used in creating the app.
- [ ]  (OPTIONAL) Deploy on netlify and share the link in readme.

P.S -> Create a new folder for the project inside the JavaScript Project. If already there then make changes to the existing one.

**Comment by unnati-dot** [comment]
I would like to work on this project . @friskycodeur Please assign me this issue.

**Comment by friskycodeur** [comment]
Sure , assigning this to you @unnati-dot
