### ISSUE TITLE
Fake Data Generator

### ISSUE THREAD

**Issue by friskycodeur** [friskycodeur/curated-project-list#15]
- [ ]  Add code files for Fake Data Generator
- [ ]  Add a readme file for Fake Data Generator (refer to other projects for format)
- [ ]  Mention resources used in creating the app.
- [ ]  (OPTIONAL) Deploy on netlify and share the link in readme.

P.S -> Create a new folder for the project inside the JavaScript Project. If already there then make changes to the existing one.

**Comment by CyrusThapa11** [comment]
I would like to work on this .

**Comment by CyrusThapa11** [comment]
@friskycodeur  I just made a pr for this . Please check  : ) . #26
