### ISSUE TITLE
Timeline app in JavaScript

### ISSUE THREAD

**Issue by friskycodeur** [friskycodeur/curated-project-list#3]
Make a timeline for events using JavaScript with visibility as users scroll down, the design would be something like this or similar :
[Design Example](https://i.pinimg.com/originals/c9/df/bd/c9dfbd857e379d9dfd0ed3c4ab58b096.png)

**Comment by VaishnaviMudaliar** [comment]
hey! can i work on this issue?

**Comment by friskycodeur** [comment]
Hey @VaishnaviMudaliar,

It's already implemented via some library , if you can do it with just vanilla JavaScript then sure go ahead!

**Comment by VaishnaviMudaliar** [comment]
alright !
