### ISSUE TITLE
Acronym Generators using Python

### ISSUE THREAD

**Issue by rudrakshi99** [friskycodeur/curated-project-list#32]
**Description:** 
An Acronym Generator will take a String as an input and it will return the initials of all the words in the String.

 * [x]  Add code files for Acronym Generator.
 * [x]  Add a readme file for Acronym Generator.
 * [x]  Mention resources used in creating the app.

**Comment by rudrakshi99** [comment]
@friskycodeur Please assign this issue to me.

**Comment by friskycodeur** [comment]
Sounds Good , assigning this to you @rudrakshi99
